name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs mkdocs-material mkdocs-jupyter beautifulsoup4      # Copy README.md to docs/index.md
      - run: |
          mkdir -p docs
          echo -e "---\nlayout: default\n---\n$(cat README.md)" > docs/index.md
      
      - run: mkdocs gh-deploy --force
